import { UserProfile, Interaction, ContactRequest, Message, Conversation, SupportTicket, SupportMessage, UserReport, Notification } from '../types';

export const ADMIN_USER: UserProfile = {
  id: 'admin_1',
  email: 'admin@wesal.app',
  role: 'admin',
  status: 'active',
  isProfileComplete: true,
  isAgeConfirmed: true,
  isTermsAccepted: true,
  createdAt: '2026-01-01T00:00:00Z',
  lastActive: new Date().toISOString(),
  isOnline: true,
  gender: 'male',
  displayName: 'إدارة منصة وصال',
  age: 35,
  birthDate: '1991-05-15',
  nationality: 'سعودي',
  country: 'المملكة العربية السعودية',
  city: 'الرياض',
  occupation: 'مدير منصة وصال',
  jobNature: 'إدارة عامة',
  education: 'دراسات عليا',
  maritalStatus: 'أعزب',
  hasChildren: false,
  desiresChildren: 'نعم',
  smoking: 'غير مدخن',
  photoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=400',
  photoReviewStatus: 'approved',
  bio: 'الحساب الرسمي لمدير منصة وصال للتعارف والزواج الجاد.',
  personalTraits: 'التزام، أمانة، تنظيم',
  hobbies: 'القراءة، التقنية',
  partnerMinAge: 22,
  partnerMaxAge: 32,
  partnerAcceptsChildren: 'نعم',
  violationCount: 0
};

export const INITIAL_MOCK_PROFILES: UserProfile[] = [
  ADMIN_USER,
  {
    id: 'user_male_1',
    email: 'ahmed@wesal.app',
    role: 'user',
    status: 'active',
    isProfileComplete: true,
    isAgeConfirmed: true,
    isTermsAccepted: true,
    createdAt: '2026-06-10T10:00:00Z',
    lastActive: new Date().toISOString(),
    isOnline: true,
    gender: 'male',
    displayName: 'أحمد العتيبي',
    age: 31,
    birthDate: '1995-03-20',
    nationality: 'سعودي',
    country: 'المملكة العربية السعودية',
    city: 'الرياض',
    occupation: 'مهندس برمجيات',
    jobNature: 'قطاع خاص - شركة تقنية',
    education: 'جامعي',
    maritalStatus: 'أعزب',
    hasChildren: false,
    desiresChildren: 'نعم',
    smoking: 'غير مدخن',
    photoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=400',
    photoReviewStatus: 'approved',
    bio: 'شاب خلوق ومصلي، أبحث عن الاستقرار والزواج الجاد لبناء أسرة سعيدة قائمة على التفاهم والمودة.',
    personalTraits: 'هادئ، طموح، كريم، يحب السفر والرياضة',
    hobbies: 'القراءة، البرمجة، القراءة، الرحلات البرية',
    partnerBio: 'أبحث عن إنسانة متخلقة، تخاف الله، خريجة جامعية، تقدر الحياة الزوجية.',
    partnerSpecs: 'أن تكون صادقة ومثقفة وتهتم بالأسرة.',
    partnerNationality: 'سعودية',
    partnerMinAge: 22,
    partnerMaxAge: 29,
    partnerEducation: 'جامعي',
    partnerMaritalStatus: 'عزباء',
    partnerAcceptsChildren: 'لا',
    partnerPreferencesNotes: 'تفضل السكن في مدينة الرياض.',
    violationCount: 0
  },
  {
    id: 'user_female_1',
    email: 'fatima@wesal.app',
    role: 'user',
    status: 'active',
    isProfileComplete: true,
    isAgeConfirmed: true,
    isTermsAccepted: true,
    createdAt: '2026-06-12T14:30:00Z',
    lastActive: new Date().toISOString(),
    isOnline: true,
    gender: 'female',
    displayName: 'فاطمة الزهراء',
    age: 26,
    birthDate: '2000-08-10',
    nationality: 'سعودية',
    country: 'المملكة العربية السعودية',
    city: 'جدة',
    occupation: 'معلمة لغة عربية',
    jobNature: 'قطاع حكومي - وزارة التعليم',
    education: 'جامعي',
    maritalStatus: 'عزباء',
    hasChildren: false,
    desiresChildren: 'نعم',
    smoking: 'غير مدخنة',
    photoUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=400',
    photoReviewStatus: 'approved',
    bio: 'فتاة محافظة، مهتمة بالثقافة والأدب، أبحث عن شريك حياة يخاف الله فيّ ويكون سندا ورفيقا.',
    personalTraits: 'طيبة القلب، مرحة، متفهمة، منظمة',
    hobbies: 'الخط العربي، القراءة، الطهي، الأشغال اليدوية',
    partnerBio: 'أبحث عن رجل مصلي، خلوق، مسؤول، يعمل بوظيفة مستقرة.',
    partnerSpecs: 'أن يكون ناضجاً ومحترماً ويقدر المشاركة والمسؤولية.',
    partnerNationality: 'سعودي',
    partnerMinAge: 27,
    partnerMaxAge: 36,
    partnerEducation: 'جامعي',
    partnerMaritalStatus: 'أعزب',
    partnerAcceptsChildren: 'حسب الحالة',
    partnerPreferencesNotes: 'يفضل من سكان منطقة مكة المكرمة أو جدة.',
    violationCount: 0
  },
  {
    id: 'user_male_2',
    email: 'tariq@wesal.app',
    role: 'user',
    status: 'active',
    isProfileComplete: true,
    isAgeConfirmed: true,
    isTermsAccepted: true,
    createdAt: '2026-06-15T09:15:00Z',
    lastActive: new Date(Date.now() - 3600000 * 2).toISOString(),
    isOnline: false,
    gender: 'male',
    displayName: 'طارق الشمري',
    age: 34,
    birthDate: '1992-01-14',
    nationality: 'سعودي',
    country: 'المملكة العربية السعودية',
    city: 'الدمام',
    occupation: 'طبيب أسنان',
    jobNature: 'مستشفى خاص',
    education: 'دراسات عليا',
    maritalStatus: 'مطلق',
    hasChildren: true,
    childrenCount: 1,
    desiresChildren: 'نعم',
    smoking: 'غير مدخن',
    photoUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=400',
    photoReviewStatus: 'approved',
    bio: 'طبيب مهتم بعمله وأسرتي، أبحث عن شريكة تناسب ظروفي وبناء بيئة أسرية دافئة.',
    personalTraits: 'حليم، كريم، متفهم، حنون',
    hobbies: 'السباحة، القراءة الطبية، السفر',
    partnerBio: 'أبحث عن إنسانة حنونة ومتفهمة تحب الأطفال وتقدر الهدوء والاستقرار.',
    partnerSpecs: 'مؤهل جامعي، محترمة وصادقة.',
    partnerNationality: 'الكل',
    partnerMinAge: 24,
    partnerMaxAge: 33,
    partnerEducation: 'جامعي',
    partnerMaritalStatus: 'الكل',
    partnerAcceptsChildren: 'نعم',
    violationCount: 0
  },
  {
    id: 'user_female_2',
    email: 'marium@wesal.app',
    role: 'user',
    status: 'active',
    isProfileComplete: true,
    isAgeConfirmed: true,
    isTermsAccepted: true,
    createdAt: '2026-06-20T18:00:00Z',
    lastActive: new Date().toISOString(),
    isOnline: true,
    gender: 'female',
    displayName: 'مريم الكواري',
    age: 28,
    birthDate: '1998-11-22',
    nationality: 'قطرية',
    country: 'قطر',
    city: 'الدوحة',
    occupation: 'مهندسة معماري',
    jobNature: 'قطاع حكومي',
    education: 'جامعي',
    maritalStatus: 'عزباء',
    hasChildren: false,
    desiresChildren: 'نعم',
    smoking: 'غير مدخنة',
    photoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=400',
    photoReviewStatus: 'approved',
    bio: 'مهندسة طموحة ومثقفة، أحب السفر والتصميم ومساعدة الآخرين. أبحث عن الزواج الشرعي الجاد.',
    personalTraits: 'إيجابية، طموحة، أنيقة، متدينة',
    hobbies: 'التصميم، التصوير، السفر، القراءة',
    partnerBio: 'أبحث عن رجل طموح، خلوق، يقدر المرأة وطموحها ويكون قادراً على تأسيس بيئة منزلية قائمة على الاحترام.',
    partnerSpecs: 'مؤهل عالٍ، مسؤول، ذو أخلاق حسنة.',
    partnerNationality: 'الخليج العربي',
    partnerMinAge: 29,
    partnerMaxAge: 38,
    partnerEducation: 'جامعي',
    partnerMaritalStatus: 'أعزب',
    partnerAcceptsChildren: 'حسب الحالة',
    violationCount: 0
  },
  {
    id: 'user_male_3',
    email: 'khalid@wesal.app',
    role: 'user',
    status: 'active',
    isProfileComplete: true,
    isAgeConfirmed: true,
    isTermsAccepted: true,
    createdAt: '2026-07-01T11:00:00Z',
    lastActive: new Date(Date.now() - 3600000 * 12).toISOString(),
    isOnline: false,
    gender: 'male',
    displayName: 'خالد المحمود',
    age: 36,
    birthDate: '1990-07-04',
    nationality: 'إماراتي',
    country: 'الإمارات العربية المتحدة',
    city: 'أبوظبي',
    occupation: 'مدير تسويق',
    jobNature: 'شركة عالمية',
    education: 'دراسات عليا',
    maritalStatus: 'أعزب',
    hasChildren: false,
    desiresChildren: 'نعم',
    smoking: 'أقلعت عن التدخين',
    photoUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&q=80&w=400',
    photoReviewStatus: 'approved',
    bio: 'رجل أعمال ومدير تسويق، أحب التطور والاستقرار. أبحث عن زوجة وتوأم روح لبدء مرحلة جديدة.',
    personalTraits: 'كريم، اجتماعي، منظم، يحب الترحال',
    hobbies: 'الرياضة، الرياضات المائية، الاستثمار',
    partnerBio: 'زوجة واعية، مثقفة، أنيقة ومحترمة.',
    partnerSpecs: 'أن تكون جادة ولديها رغبة حقيقية في الزواج والسيطرة على الحياة الأسرية بحب.',
    partnerNationality: 'الكل',
    partnerMinAge: 25,
    partnerMaxAge: 33,
    partnerEducation: 'جامعي',
    partnerMaritalStatus: 'عزباء',
    partnerAcceptsChildren: 'لا',
    violationCount: 0
  },
  {
    id: 'user_female_3',
    email: 'sara@wesal.app',
    role: 'user',
    status: 'active',
    isProfileComplete: true,
    isAgeConfirmed: true,
    isTermsAccepted: true,
    createdAt: '2026-07-05T08:20:00Z',
    lastActive: new Date().toISOString(),
    isOnline: true,
    gender: 'female',
    displayName: 'سارة فهمي',
    age: 29,
    birthDate: '1997-04-12',
    nationality: 'مصرية',
    country: 'مصر',
    city: 'القاهرة',
    occupation: 'صيدلانية',
    jobNature: 'مستشفى خاص',
    education: 'جامعي',
    maritalStatus: 'مطلقة',
    hasChildren: false,
    desiresChildren: 'نعم',
    smoking: 'غير مدخنة',
    photoUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&q=80&w=400',
    photoReviewStatus: 'approved',
    bio: 'صيدلانية هادئة ومكافحة، أبحث عن شريك حياة صادق يراعي الله في تعامله ويقدر الصراحة.',
    personalTraits: 'هادئة، متسامحة، حنونة، منظمة',
    hobbies: 'القراءة، الرسم، العناية بالنباتات',
    partnerBio: 'رجل صاحب خلق ودين، خريج مؤهل عالٍ، مسؤول وصادق.',
    partnerSpecs: 'أن يكون ناضجاً وصادقاً.',
    partnerNationality: 'مصر / السعودية / الخليج',
    partnerMinAge: 30,
    partnerMaxAge: 42,
    partnerEducation: 'جامعي',
    partnerMaritalStatus: 'الكل',
    partnerAcceptsChildren: 'نعم',
    violationCount: 0
  },
  {
    id: 'user_pending_1',
    email: 'omar@wesal.app',
    role: 'user',
    status: 'active',
    isProfileComplete: true,
    isAgeConfirmed: true,
    isTermsAccepted: true,
    createdAt: '2026-07-25T12:00:00Z',
    lastActive: new Date().toISOString(),
    isOnline: true,
    gender: 'male',
    displayName: 'عمر القحطاني',
    age: 30,
    birthDate: '1996-09-09',
    nationality: 'سعودي',
    country: 'المملكة العربية السعودية',
    city: 'أبها',
    occupation: 'محاسب قانوني',
    jobNature: 'بنك تجاري',
    education: 'جامعي',
    maritalStatus: 'أعزب',
    hasChildren: false,
    desiresChildren: 'نعم',
    smoking: 'غير مدخن',
    photoUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&q=80&w=400',
    photoReviewStatus: 'pending', // Pending Admin Photo Review
    bio: 'محاسب أبحث عن التكافؤ والاستقرار.',
    personalTraits: 'هادئ، خلوق',
    hobbies: 'المشي في الطبيعة، القراءة',
    partnerMinAge: 22,
    partnerMaxAge: 28,
    partnerAcceptsChildren: 'لا',
    violationCount: 0
  }
];

export const INITIAL_INTERACTIONS: Interaction[] = [
  {
    id: 'int_1',
    senderId: 'user_male_1',
    receiverId: 'user_female_1',
    type: 'like',
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: 'int_2',
    senderId: 'user_female_1',
    receiverId: 'user_male_1',
    type: 'flower',
    createdAt: new Date(Date.now() - 86400000 * 1).toISOString(),
  },
  {
    id: 'int_3',
    senderId: 'user_male_2',
    receiverId: 'user_female_2',
    type: 'heart',
    createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
  }
];

export const INITIAL_MUTUAL_MATCHES = [
  {
    id: 'match_1',
    user1Id: 'user_male_1',
    user2Id: 'user_female_1',
    matchedAt: new Date(Date.now() - 86400000 * 1).toISOString(),
    status: 'active' as const
  }
];

export const INITIAL_CONTACT_REQUESTS: ContactRequest[] = [
  {
    id: 'req_1',
    senderId: 'user_male_1',
    receiverId: 'user_female_1',
    createdAt: new Date(Date.now() - 3600000 * 5).toISOString(),
    status: 'pending',
    adminNote: ''
  }
];

export const INITIAL_SUPPORT_TICKETS: SupportTicket[] = [
  {
    id: 'ticket_1',
    userId: 'user_female_1',
    name: 'فاطمة الزهراء',
    email: 'fatima@wesal.app',
    subject: 'استفسار عن طريقة مراجعة طلب التواصل',
    type: 'استفسار عام',
    message: 'السلام عليكم ورحمة الله، أود الاستفسار كم يستغرق وقت مراجعة طلب التواصل من قبل إدارة منصة وصال؟ وشكراً لجهودكم المباركة.',
    createdAt: new Date(Date.now() - 86400000 * 1).toISOString(),
    status: 'in_review',
    isUrgent: false
  },
  {
    id: 'ticket_2',
    name: 'عبدالله السالم',
    email: 'abdullah@example.com',
    subject: 'طلب التثبت من شروط التسجيل',
    type: 'استفسار عن الخصوصية',
    message: 'مرحباً إدارة وصال، هل يظهر اسم العائلة الخاص بي للأعضاء؟ وأرجو توضيح معايير الأمان المتبعة.',
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    status: 'replied',
    isUrgent: false
  }
];

export const INITIAL_SUPPORT_MESSAGES: SupportMessage[] = [
  {
    id: 'smsg_1',
    ticketId: 'ticket_1',
    senderId: 'user_female_1',
    senderName: 'فاطمة الزهراء',
    isAdmin: false,
    text: 'السلام عليكم ورحمة الله، أود الاستفسار كم يستغرق وقت مراجعة طلب التواصل من قبل إدارة منصة وصال؟ وشكراً لجهودكم المباركة.',
    createdAt: new Date(Date.now() - 86400000 * 1).toISOString(),
  },
  {
    id: 'smsg_2',
    ticketId: 'ticket_1',
    senderId: 'admin_1',
    senderName: 'إدارة منصة وصال',
    isAdmin: true,
    text: 'وعليكم السلام ورحمة الله وبركاته أختنا الكريمة فاطمة. يتم مراجعة طلبات التواصل خلال مدة أقصاها 24 ساعة لضمان أمان الطرفين والتأكد من مطابقة شروط وصال.',
    createdAt: new Date(Date.now() - 3600000 * 12).toISOString(),
  },
  {
    id: 'smsg_3',
    ticketId: 'ticket_2',
    senderId: 'admin_1',
    senderName: 'إدارة منصة وصال',
    isAdmin: true,
    text: 'أهلاً بك أخي الكريم. لا يظهر اسم العائلة ولا أي بيانات شخصية أو بريد إلكتروني نهائياً للعامة أو للأعضاء. يظهر فقط الاسم الأول أو المستعار والعمر والجنسية فقط.',
    createdAt: new Date(Date.now() - 86400000 * 1).toISOString()
  }
];

export const INITIAL_NOTIFICATIONS: Notification[] = [
  {
    id: 'notif_1',
    userId: 'user_female_1',
    title: 'إعجاب جديد ❤️',
    message: 'أرسل لك العضو "أحمد العتيبي" إعجاباً بمواصفاتك.',
    type: 'like',
    isRead: false,
    createdAt: new Date(Date.now() - 86400000 * 1).toISOString()
  },
  {
    id: 'notif_2',
    userId: 'user_male_1',
    title: 'تم الإعجاب المتبادل 🎉',
    message: 'يوجد إعجاب متبادل بينك وبين "فاطمة الزهراء". يمكنك الآن تقديم طلب بدء التواصل مع الإدارة.',
    type: 'match',
    isRead: false,
    createdAt: new Date(Date.now() - 86400000 * 1).toISOString()
  }
];
